### ISSUE TITLE
Invalid HTML5

### ISSUE THREAD

**Issue by phoe** [KSIUJ/www.diamentowakreda#1]
![screenshot from 2018-06-11 11-44-15](https://user-images.githubusercontent.com/15045546/41224656-4a9414b6-6d6d-11e8-8f79-ef5a6d80e8fa.png)

**Comment by ArcCha** [comment]
Please @phoe, be more specific and paste concrete snippet of invalid code instead of a picture.

**Comment by phoe** [comment]
@ArcCha 

View the current source of https://diamentowakreda.ksi.ii.uj.edu.pl/

**Comment by m4tx** [comment]
I believe this is more descriptive:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdiamentowakreda.ksi.ii.uj.edu.pl%2F

**Comment by ArcCha** [comment]
@m4tx thanks, it's utmost helpful. @kkiermasz and @mkondratek could you please fix this?

**Comment by kkiermasz** [comment]
Oh, sorry for that mistake. I've already fixed that. It should works correctly now.
